alias bright='echo 1 | sudo tee /sys/module/sharp/parameters/mono_invert > /dev/null'
alias dark='echo 0 | sudo tee /sys/module/sharp/parameters/mono_invert > /dev/null'
alias b='echo "$(cat /sys/firmware/beepy/battery_percent) %"'
